### Introdução a Numpy


In [1]:
import numpy as np

In [4]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
b[0][0] = 2

In [7]:
print(b)


[[2 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
a[0][0] = 2

In [10]:
print(a)


[[2 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
c = (1,2,3)
print(c)


(1, 2, 3)


In [12]:
c[0] = 2

TypeError: 'tuple' object does not support item assignment

In [13]:
d = [1,2,3]
print(d)
d[0] = 2
print(d)


[1, 2, 3]
[2, 2, 3]


In [15]:
a = np.eye(4)

In [16]:
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
a = np.ones((7,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
x = 4
y = 3
arrayX = np.ones((y,x))
print(arrayX)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
a = np.eye(x*y)
print(a)




[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
lista = [i for i in "Gustavo"]
print(lista)


['G', 'u', 's', 't', 'a', 'v', 'o']
